// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: low_data/case_low_data.proto

package low_data;

public final class CaseLowData {
  private CaseLowData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComprasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:low_data.Compras)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    java.util.List<low_data.CaseLowData.Item> 
        getListaComprasList();
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    low_data.CaseLowData.Item getListaCompras(int index);
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    int getListaComprasCount();
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    java.util.List<? extends low_data.CaseLowData.ItemOrBuilder> 
        getListaComprasOrBuilderList();
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    low_data.CaseLowData.ItemOrBuilder getListaComprasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code low_data.Compras}
   */
  public static final class Compras extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:low_data.Compras)
      ComprasOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Compras.newBuilder() to construct.
    private Compras(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Compras() {
      listaCompras_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Compras();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return low_data.CaseLowData.internal_static_low_data_Compras_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return low_data.CaseLowData.internal_static_low_data_Compras_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              low_data.CaseLowData.Compras.class, low_data.CaseLowData.Compras.Builder.class);
    }

    public static final int LISTA_COMPRAS_FIELD_NUMBER = 10;
    private java.util.List<low_data.CaseLowData.Item> listaCompras_;
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    @java.lang.Override
    public java.util.List<low_data.CaseLowData.Item> getListaComprasList() {
      return listaCompras_;
    }
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    @java.lang.Override
    public java.util.List<? extends low_data.CaseLowData.ItemOrBuilder> 
        getListaComprasOrBuilderList() {
      return listaCompras_;
    }
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    @java.lang.Override
    public int getListaComprasCount() {
      return listaCompras_.size();
    }
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    @java.lang.Override
    public low_data.CaseLowData.Item getListaCompras(int index) {
      return listaCompras_.get(index);
    }
    /**
     * <code>repeated .low_data.Item lista_compras = 10;</code>
     */
    @java.lang.Override
    public low_data.CaseLowData.ItemOrBuilder getListaComprasOrBuilder(
        int index) {
      return listaCompras_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < listaCompras_.size(); i++) {
        output.writeMessage(10, listaCompras_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < listaCompras_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, listaCompras_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof low_data.CaseLowData.Compras)) {
        return super.equals(obj);
      }
      low_data.CaseLowData.Compras other = (low_data.CaseLowData.Compras) obj;

      if (!getListaComprasList()
          .equals(other.getListaComprasList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListaComprasCount() > 0) {
        hash = (37 * hash) + LISTA_COMPRAS_FIELD_NUMBER;
        hash = (53 * hash) + getListaComprasList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static low_data.CaseLowData.Compras parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static low_data.CaseLowData.Compras parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static low_data.CaseLowData.Compras parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static low_data.CaseLowData.Compras parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static low_data.CaseLowData.Compras parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static low_data.CaseLowData.Compras parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static low_data.CaseLowData.Compras parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static low_data.CaseLowData.Compras parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static low_data.CaseLowData.Compras parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static low_data.CaseLowData.Compras parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static low_data.CaseLowData.Compras parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static low_data.CaseLowData.Compras parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(low_data.CaseLowData.Compras prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code low_data.Compras}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:low_data.Compras)
        low_data.CaseLowData.ComprasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return low_data.CaseLowData.internal_static_low_data_Compras_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return low_data.CaseLowData.internal_static_low_data_Compras_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                low_data.CaseLowData.Compras.class, low_data.CaseLowData.Compras.Builder.class);
      }

      // Construct using low_data.CaseLowData.Compras.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listaComprasBuilder_ == null) {
          listaCompras_ = java.util.Collections.emptyList();
        } else {
          listaCompras_ = null;
          listaComprasBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return low_data.CaseLowData.internal_static_low_data_Compras_descriptor;
      }

      @java.lang.Override
      public low_data.CaseLowData.Compras getDefaultInstanceForType() {
        return low_data.CaseLowData.Compras.getDefaultInstance();
      }

      @java.lang.Override
      public low_data.CaseLowData.Compras build() {
        low_data.CaseLowData.Compras result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public low_data.CaseLowData.Compras buildPartial() {
        low_data.CaseLowData.Compras result = new low_data.CaseLowData.Compras(this);
        int from_bitField0_ = bitField0_;
        if (listaComprasBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            listaCompras_ = java.util.Collections.unmodifiableList(listaCompras_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.listaCompras_ = listaCompras_;
        } else {
          result.listaCompras_ = listaComprasBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof low_data.CaseLowData.Compras) {
          return mergeFrom((low_data.CaseLowData.Compras)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(low_data.CaseLowData.Compras other) {
        if (other == low_data.CaseLowData.Compras.getDefaultInstance()) return this;
        if (listaComprasBuilder_ == null) {
          if (!other.listaCompras_.isEmpty()) {
            if (listaCompras_.isEmpty()) {
              listaCompras_ = other.listaCompras_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListaComprasIsMutable();
              listaCompras_.addAll(other.listaCompras_);
            }
            onChanged();
          }
        } else {
          if (!other.listaCompras_.isEmpty()) {
            if (listaComprasBuilder_.isEmpty()) {
              listaComprasBuilder_.dispose();
              listaComprasBuilder_ = null;
              listaCompras_ = other.listaCompras_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listaComprasBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListaComprasFieldBuilder() : null;
            } else {
              listaComprasBuilder_.addAllMessages(other.listaCompras_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 82: {
                low_data.CaseLowData.Item m =
                    input.readMessage(
                        low_data.CaseLowData.Item.parser(),
                        extensionRegistry);
                if (listaComprasBuilder_ == null) {
                  ensureListaComprasIsMutable();
                  listaCompras_.add(m);
                } else {
                  listaComprasBuilder_.addMessage(m);
                }
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<low_data.CaseLowData.Item> listaCompras_ =
        java.util.Collections.emptyList();
      private void ensureListaComprasIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          listaCompras_ = new java.util.ArrayList<low_data.CaseLowData.Item>(listaCompras_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          low_data.CaseLowData.Item, low_data.CaseLowData.Item.Builder, low_data.CaseLowData.ItemOrBuilder> listaComprasBuilder_;

      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public java.util.List<low_data.CaseLowData.Item> getListaComprasList() {
        if (listaComprasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(listaCompras_);
        } else {
          return listaComprasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public int getListaComprasCount() {
        if (listaComprasBuilder_ == null) {
          return listaCompras_.size();
        } else {
          return listaComprasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public low_data.CaseLowData.Item getListaCompras(int index) {
        if (listaComprasBuilder_ == null) {
          return listaCompras_.get(index);
        } else {
          return listaComprasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder setListaCompras(
          int index, low_data.CaseLowData.Item value) {
        if (listaComprasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaComprasIsMutable();
          listaCompras_.set(index, value);
          onChanged();
        } else {
          listaComprasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder setListaCompras(
          int index, low_data.CaseLowData.Item.Builder builderForValue) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          listaCompras_.set(index, builderForValue.build());
          onChanged();
        } else {
          listaComprasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder addListaCompras(low_data.CaseLowData.Item value) {
        if (listaComprasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaComprasIsMutable();
          listaCompras_.add(value);
          onChanged();
        } else {
          listaComprasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder addListaCompras(
          int index, low_data.CaseLowData.Item value) {
        if (listaComprasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaComprasIsMutable();
          listaCompras_.add(index, value);
          onChanged();
        } else {
          listaComprasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder addListaCompras(
          low_data.CaseLowData.Item.Builder builderForValue) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          listaCompras_.add(builderForValue.build());
          onChanged();
        } else {
          listaComprasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder addListaCompras(
          int index, low_data.CaseLowData.Item.Builder builderForValue) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          listaCompras_.add(index, builderForValue.build());
          onChanged();
        } else {
          listaComprasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder addAllListaCompras(
          java.lang.Iterable<? extends low_data.CaseLowData.Item> values) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, listaCompras_);
          onChanged();
        } else {
          listaComprasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder clearListaCompras() {
        if (listaComprasBuilder_ == null) {
          listaCompras_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listaComprasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public Builder removeListaCompras(int index) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          listaCompras_.remove(index);
          onChanged();
        } else {
          listaComprasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public low_data.CaseLowData.Item.Builder getListaComprasBuilder(
          int index) {
        return getListaComprasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public low_data.CaseLowData.ItemOrBuilder getListaComprasOrBuilder(
          int index) {
        if (listaComprasBuilder_ == null) {
          return listaCompras_.get(index);  } else {
          return listaComprasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public java.util.List<? extends low_data.CaseLowData.ItemOrBuilder> 
           getListaComprasOrBuilderList() {
        if (listaComprasBuilder_ != null) {
          return listaComprasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(listaCompras_);
        }
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public low_data.CaseLowData.Item.Builder addListaComprasBuilder() {
        return getListaComprasFieldBuilder().addBuilder(
            low_data.CaseLowData.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public low_data.CaseLowData.Item.Builder addListaComprasBuilder(
          int index) {
        return getListaComprasFieldBuilder().addBuilder(
            index, low_data.CaseLowData.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .low_data.Item lista_compras = 10;</code>
       */
      public java.util.List<low_data.CaseLowData.Item.Builder> 
           getListaComprasBuilderList() {
        return getListaComprasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          low_data.CaseLowData.Item, low_data.CaseLowData.Item.Builder, low_data.CaseLowData.ItemOrBuilder> 
          getListaComprasFieldBuilder() {
        if (listaComprasBuilder_ == null) {
          listaComprasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              low_data.CaseLowData.Item, low_data.CaseLowData.Item.Builder, low_data.CaseLowData.ItemOrBuilder>(
                  listaCompras_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          listaCompras_ = null;
        }
        return listaComprasBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:low_data.Compras)
    }

    // @@protoc_insertion_point(class_scope:low_data.Compras)
    private static final low_data.CaseLowData.Compras DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new low_data.CaseLowData.Compras();
    }

    public static low_data.CaseLowData.Compras getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Compras>
        PARSER = new com.google.protobuf.AbstractParser<Compras>() {
      @java.lang.Override
      public Compras parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Compras> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Compras> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public low_data.CaseLowData.Compras getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:low_data.Item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>float quantidade = 2;</code>
     * @return The quantidade.
     */
    float getQuantidade();

    /**
     * <code>string unidade = 3;</code>
     * @return The unidade.
     */
    java.lang.String getUnidade();
    /**
     * <code>string unidade = 3;</code>
     * @return The bytes for unidade.
     */
    com.google.protobuf.ByteString
        getUnidadeBytes();
  }
  /**
   * Protobuf type {@code low_data.Item}
   */
  public static final class Item extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:low_data.Item)
      ItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Item() {
      nome_ = "";
      unidade_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Item();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return low_data.CaseLowData.internal_static_low_data_Item_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return low_data.CaseLowData.internal_static_low_data_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              low_data.CaseLowData.Item.class, low_data.CaseLowData.Item.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTIDADE_FIELD_NUMBER = 2;
    private float quantidade_;
    /**
     * <code>float quantidade = 2;</code>
     * @return The quantidade.
     */
    @java.lang.Override
    public float getQuantidade() {
      return quantidade_;
    }

    public static final int UNIDADE_FIELD_NUMBER = 3;
    private volatile java.lang.Object unidade_;
    /**
     * <code>string unidade = 3;</code>
     * @return The unidade.
     */
    @java.lang.Override
    public java.lang.String getUnidade() {
      java.lang.Object ref = unidade_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unidade_ = s;
        return s;
      }
    }
    /**
     * <code>string unidade = 3;</code>
     * @return The bytes for unidade.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnidadeBytes() {
      java.lang.Object ref = unidade_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unidade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nome_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (java.lang.Float.floatToRawIntBits(quantidade_) != 0) {
        output.writeFloat(2, quantidade_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unidade_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, unidade_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nome_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (java.lang.Float.floatToRawIntBits(quantidade_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, quantidade_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unidade_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, unidade_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof low_data.CaseLowData.Item)) {
        return super.equals(obj);
      }
      low_data.CaseLowData.Item other = (low_data.CaseLowData.Item) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (java.lang.Float.floatToIntBits(getQuantidade())
          != java.lang.Float.floatToIntBits(
              other.getQuantidade())) return false;
      if (!getUnidade()
          .equals(other.getUnidade())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + QUANTIDADE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getQuantidade());
      hash = (37 * hash) + UNIDADE_FIELD_NUMBER;
      hash = (53 * hash) + getUnidade().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static low_data.CaseLowData.Item parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static low_data.CaseLowData.Item parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static low_data.CaseLowData.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static low_data.CaseLowData.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static low_data.CaseLowData.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static low_data.CaseLowData.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static low_data.CaseLowData.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static low_data.CaseLowData.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static low_data.CaseLowData.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static low_data.CaseLowData.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static low_data.CaseLowData.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static low_data.CaseLowData.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(low_data.CaseLowData.Item prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code low_data.Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:low_data.Item)
        low_data.CaseLowData.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return low_data.CaseLowData.internal_static_low_data_Item_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return low_data.CaseLowData.internal_static_low_data_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                low_data.CaseLowData.Item.class, low_data.CaseLowData.Item.Builder.class);
      }

      // Construct using low_data.CaseLowData.Item.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";

        quantidade_ = 0F;

        unidade_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return low_data.CaseLowData.internal_static_low_data_Item_descriptor;
      }

      @java.lang.Override
      public low_data.CaseLowData.Item getDefaultInstanceForType() {
        return low_data.CaseLowData.Item.getDefaultInstance();
      }

      @java.lang.Override
      public low_data.CaseLowData.Item build() {
        low_data.CaseLowData.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public low_data.CaseLowData.Item buildPartial() {
        low_data.CaseLowData.Item result = new low_data.CaseLowData.Item(this);
        result.nome_ = nome_;
        result.quantidade_ = quantidade_;
        result.unidade_ = unidade_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof low_data.CaseLowData.Item) {
          return mergeFrom((low_data.CaseLowData.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(low_data.CaseLowData.Item other) {
        if (other == low_data.CaseLowData.Item.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (other.getQuantidade() != 0F) {
          setQuantidade(other.getQuantidade());
        }
        if (!other.getUnidade().isEmpty()) {
          unidade_ = other.unidade_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nome_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 21: {
                quantidade_ = input.readFloat();

                break;
              } // case 21
              case 26: {
                unidade_ = input.readStringRequireUtf8();

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private float quantidade_ ;
      /**
       * <code>float quantidade = 2;</code>
       * @return The quantidade.
       */
      @java.lang.Override
      public float getQuantidade() {
        return quantidade_;
      }
      /**
       * <code>float quantidade = 2;</code>
       * @param value The quantidade to set.
       * @return This builder for chaining.
       */
      public Builder setQuantidade(float value) {
        
        quantidade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float quantidade = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantidade() {
        
        quantidade_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object unidade_ = "";
      /**
       * <code>string unidade = 3;</code>
       * @return The unidade.
       */
      public java.lang.String getUnidade() {
        java.lang.Object ref = unidade_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unidade_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unidade = 3;</code>
       * @return The bytes for unidade.
       */
      public com.google.protobuf.ByteString
          getUnidadeBytes() {
        java.lang.Object ref = unidade_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unidade_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unidade = 3;</code>
       * @param value The unidade to set.
       * @return This builder for chaining.
       */
      public Builder setUnidade(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unidade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string unidade = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnidade() {
        
        unidade_ = getDefaultInstance().getUnidade();
        onChanged();
        return this;
      }
      /**
       * <code>string unidade = 3;</code>
       * @param value The bytes for unidade to set.
       * @return This builder for chaining.
       */
      public Builder setUnidadeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unidade_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:low_data.Item)
    }

    // @@protoc_insertion_point(class_scope:low_data.Item)
    private static final low_data.CaseLowData.Item DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new low_data.CaseLowData.Item();
    }

    public static low_data.CaseLowData.Item getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Item>
        PARSER = new com.google.protobuf.AbstractParser<Item>() {
      @java.lang.Override
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Item> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public low_data.CaseLowData.Item getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_low_data_Compras_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_low_data_Compras_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_low_data_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_low_data_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034low_data/case_low_data.proto\022\010low_data" +
      "\"0\n\007Compras\022%\n\rlista_compras\030\n \003(\0132\016.low" +
      "_data.Item\"9\n\004Item\022\014\n\004nome\030\001 \001(\t\022\022\n\nquan" +
      "tidade\030\002 \001(\002\022\017\n\007unidade\030\003 \001(\tB\n\n\010low_dat" +
      "ab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_low_data_Compras_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_low_data_Compras_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_low_data_Compras_descriptor,
        new java.lang.String[] { "ListaCompras", });
    internal_static_low_data_Item_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_low_data_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_low_data_Item_descriptor,
        new java.lang.String[] { "Nome", "Quantidade", "Unidade", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
