// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/big_data.proto

package data;

public final class BigData {
  private BigData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PAgendaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.PAgenda)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    java.util.List<data.BigData.PContato> 
        getContatosList();
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    data.BigData.PContato getContatos(int index);
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    int getContatosCount();
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    java.util.List<? extends data.BigData.PContatoOrBuilder> 
        getContatosOrBuilderList();
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    data.BigData.PContatoOrBuilder getContatosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code data.PAgenda}
   */
  public static final class PAgenda extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data.PAgenda)
      PAgendaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PAgenda.newBuilder() to construct.
    private PAgenda(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PAgenda() {
      contatos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PAgenda();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.BigData.internal_static_data_PAgenda_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.BigData.internal_static_data_PAgenda_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.BigData.PAgenda.class, data.BigData.PAgenda.Builder.class);
    }

    public static final int CONTATOS_FIELD_NUMBER = 10;
    private java.util.List<data.BigData.PContato> contatos_;
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    @java.lang.Override
    public java.util.List<data.BigData.PContato> getContatosList() {
      return contatos_;
    }
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    @java.lang.Override
    public java.util.List<? extends data.BigData.PContatoOrBuilder> 
        getContatosOrBuilderList() {
      return contatos_;
    }
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    @java.lang.Override
    public int getContatosCount() {
      return contatos_.size();
    }
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    @java.lang.Override
    public data.BigData.PContato getContatos(int index) {
      return contatos_.get(index);
    }
    /**
     * <code>repeated .data.PContato contatos = 10;</code>
     */
    @java.lang.Override
    public data.BigData.PContatoOrBuilder getContatosOrBuilder(
        int index) {
      return contatos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contatos_.size(); i++) {
        output.writeMessage(10, contatos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < contatos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, contatos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof data.BigData.PAgenda)) {
        return super.equals(obj);
      }
      data.BigData.PAgenda other = (data.BigData.PAgenda) obj;

      if (!getContatosList()
          .equals(other.getContatosList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContatosCount() > 0) {
        hash = (37 * hash) + CONTATOS_FIELD_NUMBER;
        hash = (53 * hash) + getContatosList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static data.BigData.PAgenda parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.BigData.PAgenda parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.BigData.PAgenda parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.BigData.PAgenda parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.BigData.PAgenda parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.BigData.PAgenda parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.BigData.PAgenda parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.BigData.PAgenda parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.BigData.PAgenda parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static data.BigData.PAgenda parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.BigData.PAgenda parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.BigData.PAgenda parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.BigData.PAgenda prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.PAgenda}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.PAgenda)
        data.BigData.PAgendaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.BigData.internal_static_data_PAgenda_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.BigData.internal_static_data_PAgenda_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.BigData.PAgenda.class, data.BigData.PAgenda.Builder.class);
      }

      // Construct using data.BigData.PAgenda.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (contatosBuilder_ == null) {
          contatos_ = java.util.Collections.emptyList();
        } else {
          contatos_ = null;
          contatosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.BigData.internal_static_data_PAgenda_descriptor;
      }

      @java.lang.Override
      public data.BigData.PAgenda getDefaultInstanceForType() {
        return data.BigData.PAgenda.getDefaultInstance();
      }

      @java.lang.Override
      public data.BigData.PAgenda build() {
        data.BigData.PAgenda result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public data.BigData.PAgenda buildPartial() {
        data.BigData.PAgenda result = new data.BigData.PAgenda(this);
        int from_bitField0_ = bitField0_;
        if (contatosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            contatos_ = java.util.Collections.unmodifiableList(contatos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contatos_ = contatos_;
        } else {
          result.contatos_ = contatosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.BigData.PAgenda) {
          return mergeFrom((data.BigData.PAgenda)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.BigData.PAgenda other) {
        if (other == data.BigData.PAgenda.getDefaultInstance()) return this;
        if (contatosBuilder_ == null) {
          if (!other.contatos_.isEmpty()) {
            if (contatos_.isEmpty()) {
              contatos_ = other.contatos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContatosIsMutable();
              contatos_.addAll(other.contatos_);
            }
            onChanged();
          }
        } else {
          if (!other.contatos_.isEmpty()) {
            if (contatosBuilder_.isEmpty()) {
              contatosBuilder_.dispose();
              contatosBuilder_ = null;
              contatos_ = other.contatos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contatosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContatosFieldBuilder() : null;
            } else {
              contatosBuilder_.addAllMessages(other.contatos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 82: {
                data.BigData.PContato m =
                    input.readMessage(
                        data.BigData.PContato.parser(),
                        extensionRegistry);
                if (contatosBuilder_ == null) {
                  ensureContatosIsMutable();
                  contatos_.add(m);
                } else {
                  contatosBuilder_.addMessage(m);
                }
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<data.BigData.PContato> contatos_ =
        java.util.Collections.emptyList();
      private void ensureContatosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          contatos_ = new java.util.ArrayList<data.BigData.PContato>(contatos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          data.BigData.PContato, data.BigData.PContato.Builder, data.BigData.PContatoOrBuilder> contatosBuilder_;

      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public java.util.List<data.BigData.PContato> getContatosList() {
        if (contatosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contatos_);
        } else {
          return contatosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public int getContatosCount() {
        if (contatosBuilder_ == null) {
          return contatos_.size();
        } else {
          return contatosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public data.BigData.PContato getContatos(int index) {
        if (contatosBuilder_ == null) {
          return contatos_.get(index);
        } else {
          return contatosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder setContatos(
          int index, data.BigData.PContato value) {
        if (contatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContatosIsMutable();
          contatos_.set(index, value);
          onChanged();
        } else {
          contatosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder setContatos(
          int index, data.BigData.PContato.Builder builderForValue) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          contatos_.set(index, builderForValue.build());
          onChanged();
        } else {
          contatosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder addContatos(data.BigData.PContato value) {
        if (contatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContatosIsMutable();
          contatos_.add(value);
          onChanged();
        } else {
          contatosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder addContatos(
          int index, data.BigData.PContato value) {
        if (contatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContatosIsMutable();
          contatos_.add(index, value);
          onChanged();
        } else {
          contatosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder addContatos(
          data.BigData.PContato.Builder builderForValue) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          contatos_.add(builderForValue.build());
          onChanged();
        } else {
          contatosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder addContatos(
          int index, data.BigData.PContato.Builder builderForValue) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          contatos_.add(index, builderForValue.build());
          onChanged();
        } else {
          contatosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder addAllContatos(
          java.lang.Iterable<? extends data.BigData.PContato> values) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contatos_);
          onChanged();
        } else {
          contatosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder clearContatos() {
        if (contatosBuilder_ == null) {
          contatos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contatosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public Builder removeContatos(int index) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          contatos_.remove(index);
          onChanged();
        } else {
          contatosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public data.BigData.PContato.Builder getContatosBuilder(
          int index) {
        return getContatosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public data.BigData.PContatoOrBuilder getContatosOrBuilder(
          int index) {
        if (contatosBuilder_ == null) {
          return contatos_.get(index);  } else {
          return contatosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public java.util.List<? extends data.BigData.PContatoOrBuilder> 
           getContatosOrBuilderList() {
        if (contatosBuilder_ != null) {
          return contatosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contatos_);
        }
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public data.BigData.PContato.Builder addContatosBuilder() {
        return getContatosFieldBuilder().addBuilder(
            data.BigData.PContato.getDefaultInstance());
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public data.BigData.PContato.Builder addContatosBuilder(
          int index) {
        return getContatosFieldBuilder().addBuilder(
            index, data.BigData.PContato.getDefaultInstance());
      }
      /**
       * <code>repeated .data.PContato contatos = 10;</code>
       */
      public java.util.List<data.BigData.PContato.Builder> 
           getContatosBuilderList() {
        return getContatosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          data.BigData.PContato, data.BigData.PContato.Builder, data.BigData.PContatoOrBuilder> 
          getContatosFieldBuilder() {
        if (contatosBuilder_ == null) {
          contatosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              data.BigData.PContato, data.BigData.PContato.Builder, data.BigData.PContatoOrBuilder>(
                  contatos_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          contatos_ = null;
        }
        return contatosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data.PAgenda)
    }

    // @@protoc_insertion_point(class_scope:data.PAgenda)
    private static final data.BigData.PAgenda DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.BigData.PAgenda();
    }

    public static data.BigData.PAgenda getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PAgenda>
        PARSER = new com.google.protobuf.AbstractParser<PAgenda>() {
      @java.lang.Override
      public PAgenda parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PAgenda> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PAgenda> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public data.BigData.PAgenda getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PContatoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.PContato)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string telefone = 2;</code>
     * @return The telefone.
     */
    java.lang.String getTelefone();
    /**
     * <code>string telefone = 2;</code>
     * @return The bytes for telefone.
     */
    com.google.protobuf.ByteString
        getTelefoneBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string foto = 4;</code>
     * @return The foto.
     */
    java.lang.String getFoto();
    /**
     * <code>string foto = 4;</code>
     * @return The bytes for foto.
     */
    com.google.protobuf.ByteString
        getFotoBytes();
  }
  /**
   * Protobuf type {@code data.PContato}
   */
  public static final class PContato extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data.PContato)
      PContatoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PContato.newBuilder() to construct.
    private PContato(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PContato() {
      nome_ = "";
      telefone_ = "";
      email_ = "";
      foto_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PContato();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.BigData.internal_static_data_PContato_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.BigData.internal_static_data_PContato_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.BigData.PContato.class, data.BigData.PContato.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TELEFONE_FIELD_NUMBER = 2;
    private volatile java.lang.Object telefone_;
    /**
     * <code>string telefone = 2;</code>
     * @return The telefone.
     */
    @java.lang.Override
    public java.lang.String getTelefone() {
      java.lang.Object ref = telefone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        telefone_ = s;
        return s;
      }
    }
    /**
     * <code>string telefone = 2;</code>
     * @return The bytes for telefone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTelefoneBytes() {
      java.lang.Object ref = telefone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telefone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FOTO_FIELD_NUMBER = 4;
    private volatile java.lang.Object foto_;
    /**
     * <code>string foto = 4;</code>
     * @return The foto.
     */
    @java.lang.Override
    public java.lang.String getFoto() {
      java.lang.Object ref = foto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foto_ = s;
        return s;
      }
    }
    /**
     * <code>string foto = 4;</code>
     * @return The bytes for foto.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFotoBytes() {
      java.lang.Object ref = foto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nome_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(telefone_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, telefone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foto_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, foto_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nome_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(telefone_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, telefone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foto_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, foto_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof data.BigData.PContato)) {
        return super.equals(obj);
      }
      data.BigData.PContato other = (data.BigData.PContato) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (!getTelefone()
          .equals(other.getTelefone())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getFoto()
          .equals(other.getFoto())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + TELEFONE_FIELD_NUMBER;
      hash = (53 * hash) + getTelefone().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + FOTO_FIELD_NUMBER;
      hash = (53 * hash) + getFoto().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static data.BigData.PContato parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.BigData.PContato parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.BigData.PContato parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.BigData.PContato parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.BigData.PContato parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.BigData.PContato parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.BigData.PContato parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.BigData.PContato parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.BigData.PContato parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static data.BigData.PContato parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.BigData.PContato parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.BigData.PContato parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.BigData.PContato prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.PContato}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.PContato)
        data.BigData.PContatoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.BigData.internal_static_data_PContato_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.BigData.internal_static_data_PContato_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.BigData.PContato.class, data.BigData.PContato.Builder.class);
      }

      // Construct using data.BigData.PContato.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";

        telefone_ = "";

        email_ = "";

        foto_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.BigData.internal_static_data_PContato_descriptor;
      }

      @java.lang.Override
      public data.BigData.PContato getDefaultInstanceForType() {
        return data.BigData.PContato.getDefaultInstance();
      }

      @java.lang.Override
      public data.BigData.PContato build() {
        data.BigData.PContato result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public data.BigData.PContato buildPartial() {
        data.BigData.PContato result = new data.BigData.PContato(this);
        result.nome_ = nome_;
        result.telefone_ = telefone_;
        result.email_ = email_;
        result.foto_ = foto_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.BigData.PContato) {
          return mergeFrom((data.BigData.PContato)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.BigData.PContato other) {
        if (other == data.BigData.PContato.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (!other.getTelefone().isEmpty()) {
          telefone_ = other.telefone_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getFoto().isEmpty()) {
          foto_ = other.foto_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nome_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                telefone_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                email_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                foto_ = input.readStringRequireUtf8();

                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object telefone_ = "";
      /**
       * <code>string telefone = 2;</code>
       * @return The telefone.
       */
      public java.lang.String getTelefone() {
        java.lang.Object ref = telefone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          telefone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string telefone = 2;</code>
       * @return The bytes for telefone.
       */
      public com.google.protobuf.ByteString
          getTelefoneBytes() {
        java.lang.Object ref = telefone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          telefone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string telefone = 2;</code>
       * @param value The telefone to set.
       * @return This builder for chaining.
       */
      public Builder setTelefone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        telefone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string telefone = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTelefone() {
        
        telefone_ = getDefaultInstance().getTelefone();
        onChanged();
        return this;
      }
      /**
       * <code>string telefone = 2;</code>
       * @param value The bytes for telefone to set.
       * @return This builder for chaining.
       */
      public Builder setTelefoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        telefone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object foto_ = "";
      /**
       * <code>string foto = 4;</code>
       * @return The foto.
       */
      public java.lang.String getFoto() {
        java.lang.Object ref = foto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          foto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string foto = 4;</code>
       * @return The bytes for foto.
       */
      public com.google.protobuf.ByteString
          getFotoBytes() {
        java.lang.Object ref = foto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          foto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string foto = 4;</code>
       * @param value The foto to set.
       * @return This builder for chaining.
       */
      public Builder setFoto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        foto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string foto = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFoto() {
        
        foto_ = getDefaultInstance().getFoto();
        onChanged();
        return this;
      }
      /**
       * <code>string foto = 4;</code>
       * @param value The bytes for foto to set.
       * @return This builder for chaining.
       */
      public Builder setFotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        foto_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data.PContato)
    }

    // @@protoc_insertion_point(class_scope:data.PContato)
    private static final data.BigData.PContato DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.BigData.PContato();
    }

    public static data.BigData.PContato getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PContato>
        PARSER = new com.google.protobuf.AbstractParser<PContato>() {
      @java.lang.Override
      public PContato parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PContato> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PContato> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public data.BigData.PContato getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_PAgenda_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_PAgenda_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_PContato_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_PContato_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/java/big_data.proto\022\004data\"+\n\007" +
      "PAgenda\022 \n\010contatos\030\n \003(\0132\016.data.PContat" +
      "o\"G\n\010PContato\022\014\n\004nome\030\001 \001(\t\022\020\n\010telefone\030" +
      "\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\014\n\004foto\030\004 \001(\tB\006\n\004da" +
      "tab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_data_PAgenda_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_PAgenda_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_PAgenda_descriptor,
        new java.lang.String[] { "Contatos", });
    internal_static_data_PContato_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_PContato_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_PContato_descriptor,
        new java.lang.String[] { "Nome", "Telefone", "Email", "Foto", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
