// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/low_data.proto

package data;

public final class LowData {
  private LowData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PComprasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.PCompras)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    java.util.List<data.LowData.PItem> 
        getListaComprasList();
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    data.LowData.PItem getListaCompras(int index);
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    int getListaComprasCount();
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    java.util.List<? extends data.LowData.PItemOrBuilder> 
        getListaComprasOrBuilderList();
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    data.LowData.PItemOrBuilder getListaComprasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code data.PCompras}
   */
  public static final class PCompras extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data.PCompras)
      PComprasOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PCompras.newBuilder() to construct.
    private PCompras(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PCompras() {
      listaCompras_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PCompras();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.LowData.internal_static_data_PCompras_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.LowData.internal_static_data_PCompras_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.LowData.PCompras.class, data.LowData.PCompras.Builder.class);
    }

    public static final int LISTA_COMPRAS_FIELD_NUMBER = 10;
    private java.util.List<data.LowData.PItem> listaCompras_;
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    @java.lang.Override
    public java.util.List<data.LowData.PItem> getListaComprasList() {
      return listaCompras_;
    }
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    @java.lang.Override
    public java.util.List<? extends data.LowData.PItemOrBuilder> 
        getListaComprasOrBuilderList() {
      return listaCompras_;
    }
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    @java.lang.Override
    public int getListaComprasCount() {
      return listaCompras_.size();
    }
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    @java.lang.Override
    public data.LowData.PItem getListaCompras(int index) {
      return listaCompras_.get(index);
    }
    /**
     * <code>repeated .data.PItem lista_compras = 10;</code>
     */
    @java.lang.Override
    public data.LowData.PItemOrBuilder getListaComprasOrBuilder(
        int index) {
      return listaCompras_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < listaCompras_.size(); i++) {
        output.writeMessage(10, listaCompras_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < listaCompras_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, listaCompras_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof data.LowData.PCompras)) {
        return super.equals(obj);
      }
      data.LowData.PCompras other = (data.LowData.PCompras) obj;

      if (!getListaComprasList()
          .equals(other.getListaComprasList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListaComprasCount() > 0) {
        hash = (37 * hash) + LISTA_COMPRAS_FIELD_NUMBER;
        hash = (53 * hash) + getListaComprasList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static data.LowData.PCompras parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LowData.PCompras parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LowData.PCompras parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LowData.PCompras parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LowData.PCompras parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LowData.PCompras parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LowData.PCompras parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.LowData.PCompras parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.LowData.PCompras parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static data.LowData.PCompras parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.LowData.PCompras parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.LowData.PCompras parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.LowData.PCompras prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.PCompras}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.PCompras)
        data.LowData.PComprasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.LowData.internal_static_data_PCompras_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.LowData.internal_static_data_PCompras_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.LowData.PCompras.class, data.LowData.PCompras.Builder.class);
      }

      // Construct using data.LowData.PCompras.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (listaComprasBuilder_ == null) {
          listaCompras_ = java.util.Collections.emptyList();
        } else {
          listaCompras_ = null;
          listaComprasBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.LowData.internal_static_data_PCompras_descriptor;
      }

      @java.lang.Override
      public data.LowData.PCompras getDefaultInstanceForType() {
        return data.LowData.PCompras.getDefaultInstance();
      }

      @java.lang.Override
      public data.LowData.PCompras build() {
        data.LowData.PCompras result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public data.LowData.PCompras buildPartial() {
        data.LowData.PCompras result = new data.LowData.PCompras(this);
        int from_bitField0_ = bitField0_;
        if (listaComprasBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            listaCompras_ = java.util.Collections.unmodifiableList(listaCompras_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.listaCompras_ = listaCompras_;
        } else {
          result.listaCompras_ = listaComprasBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.LowData.PCompras) {
          return mergeFrom((data.LowData.PCompras)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.LowData.PCompras other) {
        if (other == data.LowData.PCompras.getDefaultInstance()) return this;
        if (listaComprasBuilder_ == null) {
          if (!other.listaCompras_.isEmpty()) {
            if (listaCompras_.isEmpty()) {
              listaCompras_ = other.listaCompras_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListaComprasIsMutable();
              listaCompras_.addAll(other.listaCompras_);
            }
            onChanged();
          }
        } else {
          if (!other.listaCompras_.isEmpty()) {
            if (listaComprasBuilder_.isEmpty()) {
              listaComprasBuilder_.dispose();
              listaComprasBuilder_ = null;
              listaCompras_ = other.listaCompras_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listaComprasBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListaComprasFieldBuilder() : null;
            } else {
              listaComprasBuilder_.addAllMessages(other.listaCompras_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 82: {
                data.LowData.PItem m =
                    input.readMessage(
                        data.LowData.PItem.parser(),
                        extensionRegistry);
                if (listaComprasBuilder_ == null) {
                  ensureListaComprasIsMutable();
                  listaCompras_.add(m);
                } else {
                  listaComprasBuilder_.addMessage(m);
                }
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<data.LowData.PItem> listaCompras_ =
        java.util.Collections.emptyList();
      private void ensureListaComprasIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          listaCompras_ = new java.util.ArrayList<data.LowData.PItem>(listaCompras_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          data.LowData.PItem, data.LowData.PItem.Builder, data.LowData.PItemOrBuilder> listaComprasBuilder_;

      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public java.util.List<data.LowData.PItem> getListaComprasList() {
        if (listaComprasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(listaCompras_);
        } else {
          return listaComprasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public int getListaComprasCount() {
        if (listaComprasBuilder_ == null) {
          return listaCompras_.size();
        } else {
          return listaComprasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public data.LowData.PItem getListaCompras(int index) {
        if (listaComprasBuilder_ == null) {
          return listaCompras_.get(index);
        } else {
          return listaComprasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder setListaCompras(
          int index, data.LowData.PItem value) {
        if (listaComprasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaComprasIsMutable();
          listaCompras_.set(index, value);
          onChanged();
        } else {
          listaComprasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder setListaCompras(
          int index, data.LowData.PItem.Builder builderForValue) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          listaCompras_.set(index, builderForValue.build());
          onChanged();
        } else {
          listaComprasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder addListaCompras(data.LowData.PItem value) {
        if (listaComprasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaComprasIsMutable();
          listaCompras_.add(value);
          onChanged();
        } else {
          listaComprasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder addListaCompras(
          int index, data.LowData.PItem value) {
        if (listaComprasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListaComprasIsMutable();
          listaCompras_.add(index, value);
          onChanged();
        } else {
          listaComprasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder addListaCompras(
          data.LowData.PItem.Builder builderForValue) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          listaCompras_.add(builderForValue.build());
          onChanged();
        } else {
          listaComprasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder addListaCompras(
          int index, data.LowData.PItem.Builder builderForValue) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          listaCompras_.add(index, builderForValue.build());
          onChanged();
        } else {
          listaComprasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder addAllListaCompras(
          java.lang.Iterable<? extends data.LowData.PItem> values) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, listaCompras_);
          onChanged();
        } else {
          listaComprasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder clearListaCompras() {
        if (listaComprasBuilder_ == null) {
          listaCompras_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listaComprasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public Builder removeListaCompras(int index) {
        if (listaComprasBuilder_ == null) {
          ensureListaComprasIsMutable();
          listaCompras_.remove(index);
          onChanged();
        } else {
          listaComprasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public data.LowData.PItem.Builder getListaComprasBuilder(
          int index) {
        return getListaComprasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public data.LowData.PItemOrBuilder getListaComprasOrBuilder(
          int index) {
        if (listaComprasBuilder_ == null) {
          return listaCompras_.get(index);  } else {
          return listaComprasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public java.util.List<? extends data.LowData.PItemOrBuilder> 
           getListaComprasOrBuilderList() {
        if (listaComprasBuilder_ != null) {
          return listaComprasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(listaCompras_);
        }
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public data.LowData.PItem.Builder addListaComprasBuilder() {
        return getListaComprasFieldBuilder().addBuilder(
            data.LowData.PItem.getDefaultInstance());
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public data.LowData.PItem.Builder addListaComprasBuilder(
          int index) {
        return getListaComprasFieldBuilder().addBuilder(
            index, data.LowData.PItem.getDefaultInstance());
      }
      /**
       * <code>repeated .data.PItem lista_compras = 10;</code>
       */
      public java.util.List<data.LowData.PItem.Builder> 
           getListaComprasBuilderList() {
        return getListaComprasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          data.LowData.PItem, data.LowData.PItem.Builder, data.LowData.PItemOrBuilder> 
          getListaComprasFieldBuilder() {
        if (listaComprasBuilder_ == null) {
          listaComprasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              data.LowData.PItem, data.LowData.PItem.Builder, data.LowData.PItemOrBuilder>(
                  listaCompras_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          listaCompras_ = null;
        }
        return listaComprasBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data.PCompras)
    }

    // @@protoc_insertion_point(class_scope:data.PCompras)
    private static final data.LowData.PCompras DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.LowData.PCompras();
    }

    public static data.LowData.PCompras getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PCompras>
        PARSER = new com.google.protobuf.AbstractParser<PCompras>() {
      @java.lang.Override
      public PCompras parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PCompras> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PCompras> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public data.LowData.PCompras getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.PItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>float quantidade = 2;</code>
     * @return The quantidade.
     */
    float getQuantidade();

    /**
     * <code>string unidade = 3;</code>
     * @return The unidade.
     */
    java.lang.String getUnidade();
    /**
     * <code>string unidade = 3;</code>
     * @return The bytes for unidade.
     */
    com.google.protobuf.ByteString
        getUnidadeBytes();
  }
  /**
   * Protobuf type {@code data.PItem}
   */
  public static final class PItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:data.PItem)
      PItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PItem.newBuilder() to construct.
    private PItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PItem() {
      nome_ = "";
      unidade_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PItem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.LowData.internal_static_data_PItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.LowData.internal_static_data_PItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.LowData.PItem.class, data.LowData.PItem.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTIDADE_FIELD_NUMBER = 2;
    private float quantidade_;
    /**
     * <code>float quantidade = 2;</code>
     * @return The quantidade.
     */
    @java.lang.Override
    public float getQuantidade() {
      return quantidade_;
    }

    public static final int UNIDADE_FIELD_NUMBER = 3;
    private volatile java.lang.Object unidade_;
    /**
     * <code>string unidade = 3;</code>
     * @return The unidade.
     */
    @java.lang.Override
    public java.lang.String getUnidade() {
      java.lang.Object ref = unidade_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unidade_ = s;
        return s;
      }
    }
    /**
     * <code>string unidade = 3;</code>
     * @return The bytes for unidade.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnidadeBytes() {
      java.lang.Object ref = unidade_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unidade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nome_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (java.lang.Float.floatToRawIntBits(quantidade_) != 0) {
        output.writeFloat(2, quantidade_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unidade_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, unidade_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nome_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (java.lang.Float.floatToRawIntBits(quantidade_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, quantidade_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unidade_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, unidade_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof data.LowData.PItem)) {
        return super.equals(obj);
      }
      data.LowData.PItem other = (data.LowData.PItem) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (java.lang.Float.floatToIntBits(getQuantidade())
          != java.lang.Float.floatToIntBits(
              other.getQuantidade())) return false;
      if (!getUnidade()
          .equals(other.getUnidade())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + QUANTIDADE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getQuantidade());
      hash = (37 * hash) + UNIDADE_FIELD_NUMBER;
      hash = (53 * hash) + getUnidade().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static data.LowData.PItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LowData.PItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LowData.PItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LowData.PItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LowData.PItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.LowData.PItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.LowData.PItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.LowData.PItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.LowData.PItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static data.LowData.PItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static data.LowData.PItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static data.LowData.PItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.LowData.PItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.PItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.PItem)
        data.LowData.PItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.LowData.internal_static_data_PItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.LowData.internal_static_data_PItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.LowData.PItem.class, data.LowData.PItem.Builder.class);
      }

      // Construct using data.LowData.PItem.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";

        quantidade_ = 0F;

        unidade_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.LowData.internal_static_data_PItem_descriptor;
      }

      @java.lang.Override
      public data.LowData.PItem getDefaultInstanceForType() {
        return data.LowData.PItem.getDefaultInstance();
      }

      @java.lang.Override
      public data.LowData.PItem build() {
        data.LowData.PItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public data.LowData.PItem buildPartial() {
        data.LowData.PItem result = new data.LowData.PItem(this);
        result.nome_ = nome_;
        result.quantidade_ = quantidade_;
        result.unidade_ = unidade_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.LowData.PItem) {
          return mergeFrom((data.LowData.PItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.LowData.PItem other) {
        if (other == data.LowData.PItem.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (other.getQuantidade() != 0F) {
          setQuantidade(other.getQuantidade());
        }
        if (!other.getUnidade().isEmpty()) {
          unidade_ = other.unidade_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nome_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 21: {
                quantidade_ = input.readFloat();

                break;
              } // case 21
              case 26: {
                unidade_ = input.readStringRequireUtf8();

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private float quantidade_ ;
      /**
       * <code>float quantidade = 2;</code>
       * @return The quantidade.
       */
      @java.lang.Override
      public float getQuantidade() {
        return quantidade_;
      }
      /**
       * <code>float quantidade = 2;</code>
       * @param value The quantidade to set.
       * @return This builder for chaining.
       */
      public Builder setQuantidade(float value) {
        
        quantidade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float quantidade = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantidade() {
        
        quantidade_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object unidade_ = "";
      /**
       * <code>string unidade = 3;</code>
       * @return The unidade.
       */
      public java.lang.String getUnidade() {
        java.lang.Object ref = unidade_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unidade_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unidade = 3;</code>
       * @return The bytes for unidade.
       */
      public com.google.protobuf.ByteString
          getUnidadeBytes() {
        java.lang.Object ref = unidade_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unidade_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unidade = 3;</code>
       * @param value The unidade to set.
       * @return This builder for chaining.
       */
      public Builder setUnidade(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unidade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string unidade = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnidade() {
        
        unidade_ = getDefaultInstance().getUnidade();
        onChanged();
        return this;
      }
      /**
       * <code>string unidade = 3;</code>
       * @param value The bytes for unidade to set.
       * @return This builder for chaining.
       */
      public Builder setUnidadeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unidade_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:data.PItem)
    }

    // @@protoc_insertion_point(class_scope:data.PItem)
    private static final data.LowData.PItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.LowData.PItem();
    }

    public static data.LowData.PItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PItem>
        PARSER = new com.google.protobuf.AbstractParser<PItem>() {
      @java.lang.Override
      public PItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public data.LowData.PItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_PCompras_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_PCompras_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_PItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_PItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/java/low_data.proto\022\004data\".\n\010" +
      "PCompras\022\"\n\rlista_compras\030\n \003(\0132\013.data.P" +
      "Item\":\n\005PItem\022\014\n\004nome\030\001 \001(\t\022\022\n\nquantidad" +
      "e\030\002 \001(\002\022\017\n\007unidade\030\003 \001(\tB\006\n\004datab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_data_PCompras_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_PCompras_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_PCompras_descriptor,
        new java.lang.String[] { "ListaCompras", });
    internal_static_data_PItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_PItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_PItem_descriptor,
        new java.lang.String[] { "Nome", "Quantidade", "Unidade", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
